require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'spec/dummy/db/schema.rb'
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^# [^\n]+'

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Rails/DynamicFindBy:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods:
    - increment!
    - decrement!
    - touch

RSpec/ExampleLength:
  Max: 10

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Max: 5

RSpecRails/NegationBeValid:
  EnforcedStyle: be_invalid

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: template
