# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'argon2', '~> 2.1'
gem 'blind_index', '~> 2.3'
gem 'blueprinter', '~> 0.25'
gem 'bootsnap', require: false
gem 'graphql', '~> 2.0'
gem 'graphql-rails_logger'
gem 'has_unique_attribute', '~> 0.1.3'
gem 'image_processing', '~> 1.2'
gem 'lockbox', '~> 1.1'
gem 'oj', '~> 3.13'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.0'
gem 'pundit', '~> 2.3'
gem 'rails', '~> 7.0.4'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'valid_email2', '~> 4.0'
gem 'where_any', '~> 0.1', '>= 0.1.1'

group :development do
  gem 'annotate'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'pundit-matchers', '~> 1.8.4'
  gem 'rspec-rails'
end
